-- 오라클 인덱스 실습
-- 1. 100만개의 데이터를 넣을 테이블 생성
-- 2. 100만개 데이터 삽입(PL/SQL 반복문)
-- 3. 인덱스 설정 전 테스트
-- 4. 인덱스 설정
-- 5. 인덱스 설정 후 테스트

-- #1
-- 테이블 명 : KH_CUSTOMER_TBL
-- 컬럼 : 아이디, 비밀번호, 이름, 전화번호, 주소, 등록일, 수정일

CREATE TABLE KH_CUSTOMER_TBL(
    USER_ID VARCHAR2(20),
    USER_PW VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_PHONE VARCHAR2(30),
    USER_ADDR VARCHAR2(500),
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    FIX_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- #2 시퀀스 생성
CREATE SEQUENCE SEQ_CUSTOMER_USERID
MINVALUE 1
MAXVALUE 99999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


DECLARE
    V_USERID VARCHAR2(200);
BEGIN
    FOR N IN 1..1000000
    LOOP
        V_USERID := '1'||LPAD(SEQ_CUSTOMER_USERID.NEXTVAL, 9, 0); -- LPAD : 왼쪽의 공간에 숫자만큼 숫자나 문자를 채움(여기선 9개의 0을 채움)
        INSERT INTO KH_CUSTOMER_TBL
        VALUES(V_USERID, '0000', N || '용자', '010-0000-0000',
        '서울시 중구 남대문로' || N, DEFAULT, DEFAULT);
    END LOOP;
END;
/

SELECT * FROM KH_CUSTOMER_TBL;
DROP SEQUENCE SEQ_CUSTOMER_USERID;
DELETE FROM KH_CUSTOMER_TBL;
DROP TABLE KH_CUSTOMER_TBL;


-- #3
-- 인덱스 걸기 전 실행시간 체크
EXPLAIN PLAN FOR
SELECT * FROM KH_CUSTOMER_TBL
WHERE USER_NAME LIKE '22%용자';
-- 설명되었습니다.

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- 4047   (1)| 00:00:49, TABLE ACCESS FULL

-- #4
-- 인덱스 생성하기
CREATE INDEX IDX_CUSTOMER_USERNAME ON KH_CUSTOMER_TBL(USER_NAME);

-- INDEX IDX_CUSTOMER_USERNAME이 생성되었습니다.


-- #5
-- 인덱스 건 후 실행시간 체크
EXPLAIN PLAN FOR
SELECT * FROM KH_CUSTOMER_TBL
WHERE USER_NAME LIKE '22%용자';
-- 설명되었습니다.
--> DBMS_XPLAN.DISPLAY로 확인 가능


SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- 1852, 00:00:23, 00:00:01, TABLE ACCESS BY INDEX ROWID(23초), INDEX RANGE SCAN(1초)


-- 인덱스 삭제
DROP INDEX IDX_CUSTOMER_USERNAME;




