-- 3일차
-- DDL, Data Definition Language 데이터 정의어
-- CREATE, ALTER, DROP             DDL의 종류
-- CREATE USER, CREATE TABLE..     예시
-- DROP TABLE..
-- ALTER로 할 수 있었던 것
-- 컬럼추가, 컬럼삭제, 커럼수정(데이터타입, 이름), 테이블명 수정

-- ex01) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 추가해주세요
DESC USER_FOREIGN_KEY;
ALTER TABLE USER_FOREIGN_KEY ADD USER_DATE DATE;
-- ex02) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 삭제해주세요
ALTER TABLE USER_FOREIGN_KEY DROP COLUMN USER_DATE;
-- ex03) USER_FOREIGN_KEY 테이블에 USER_DATE 컬럼의 자료형을 VARCHAR2(10)으로 바꿔주세요
ALTER TABLE USER_FOREIGN_KEY MODIFY USER_DATE VARCHAR(10);
-- ex04) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼의 이름을 REG_DATE로 변경해주세요
ALTER TABLE USER_FOREIGN_KEY RENAME COLUMN USER_DATE TO REG_DATE2;

-- ex05) USER_FOREIGN_KEY 테이블의 이름을 USER_TBL로 바꿔주세요 (2가지)
ALTER TABLE USER_FOREIGN_KEY RENAME TO USER_TBL;
RENAME USER_TBL TO USER_FOREIGN_KEY;


-- 제약조건 추가, 삭제, 수정
SELECT * FROM user_constraints WHERE TABLE_NAME = 'USER_TBL';
--!! 제약조건 추가에서 NOT NULL 추가는 좀 다른방식!!
ALTER TABLE USER_TBL MODIFY USER_ID NOT NULL; -- not null은 따로 제약조건이름을 붙이지 않음
-- !! DEFAULT도 MODIFY로 추가
ALTER TABLE USER_TBL MODIFY USER_DATE DEFAULT SYSDATE;

-- USER_GRADE에 primary key 생성
ALTER TABLE USER_GRADE ADD CONSTRAINT PK_GRADE_CODE PRIMARY KEY(GRADE_CODE);

-- USER_TBL에 foreign key 생성 및 primary key랑 연결
ALTER TABLE USER_TBL ADD CONSTRAINT FK_GRADE_CODE
FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE); 

-- key(제약조건) 삭제
ALTER TABLE USER_GRADE DROP CONSTRAINT PK_GRADE_CODE;
ALTER TABLE USER_TBL DROP CONSTRAINT FK_GRADE_CODE;

-- 실습 --
-- key 조회
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='USER_GRADE';
-- key 삭제
ALTER TABLE USER_GRADE DROP CONSTRAINT PK_GRADE_CODE;
-- key 생성
ALTER TABLE USER_GRADE ADD CONSTRAINT PK_GRADE_CODE PRIMARY KEY(GRADE_CODE);

-- 제약 조건 수정!!--
-- 제약 조건 수정은 삭제하고 추가하는 것, 단 이름을 바꿀 수 있음
ALTER TABLE USER_GRADE
RENAME CONSTRAINT PK_GRADE_CODE TO PRIMARYKEY_GR_CODE;


-- 제약 조건 활성화/비활성화 --
-- 활성화
ALTER TABLE USER_TBL DISABLE CONSTRAINT FK_GRADE_CODE;
-- 비활성화
ALTER TABLE USER_TBL ENABLE CONSTRAINT FK_GRADE_CODE;

-- 활성화/비활성화 조회 => 제약조건에서 STATUS필드 확인!
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='USER_TBL';

COMMIT;