CREATE TABLE TB_DEPARTMENT(
    DEPARTMENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(20),
    OPEN_YN CHAR(1),
    CAPACITY NUMBER
);

DESC TB_DEPARTMENT;


CREATE TABLE TB_STUDENT(
    STUDENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO) NOT NULL,
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_SSN VARCHAR2(14),
    STUDENT_ADDRESS VARCHAR2(100),
    ENTRANCE_DATE DATE,
    ABSENCE_YN CHAR(1) CHECK (ABSENCE_YN IN('Y','N')),
    COACH_PROFESSOR_NO VARCHAR2(10)
);
-- prfessor_No 외래키 생성해주어야함
-- REFERENCES TB_PROFESSOR(PROFESSOR_NO)
ALTER TABLE TB_STUDENT ADD CONSTRAINT FK_PROFESSOR_NO FOREIGN KEY(COACH_PROFESSOR_NO)
REFERENCES TB_PROFESSOR(PROFESSOR_NO);

DESC TB_STUDENT;



CREATE TABLE TB_CLASS(
    CLASS_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO) NOT NULL,
    PREATTENDING_CLASS_NO VARCHAR2(10),
    CLASS_NAME VARCHAR2(30) NOT NULL,
    CLASS_TYPE VARCHAR2(10)
);
DROP TABLE TB_CLASS;
--preattending class no 외래키 생성 해주어야함
ALTER TABLE TB_CLASS ADD CONSTRAINT FK_PREATTENDING_CLASS_NO FOREIGN KEY(PREATTENDING_CLASS_NO)
REFERENCES TB_GRADE(CLASS_NO);

CREATE TABLE TB_CLASS_PROFESSOR(
    CLASS_NO VARCHAR2(10) REFERENCES TB_CLASS(CLASS_NO) PRIMARY KEY,
    PROFESSOR_NO VARCHAR2(10) PRIMARY KEY
);
-- professor no 외래키 지정 해줘야함


CREATE TABLE TB_PROFESSOR(
    PROFESSOR_NO VARCHAR2(10) PRIMARY KEY,
    PROFESSOR_NAME VARCHAR2(30) NOT NULL,
    PROFESSOR_SSN VARCHAR2(14),
    PROFESSOR_ADDRESS VARCHAR2(100),
    DEPARTMENT_NO VARCHAR2(10) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO)
);

DESC TB_PROFESSOR;

CREATE TABLE TB_GRADE(
    TERM_NO VARCHAR2(10) PRIMARY KEY,
    CLASS_NO VARCHAR2(10)REFERENCES TB_CLASS(CLASS_NO),
    STUDENT_NO VARCHAR2(10) REFERENCES TB_STUDENT(STUDENT_NO),
    POINT NUMBER(3,2)
);
DROP TABLE TB_GRADE;
DESC TB_GRADE;
    